CREATE TABLE `wbd_pdct` (
`id` INT(25) NOT NULL AUTO_INCREMENT ,
`ttl` VARCHAR(255) NOT NULL ,
`ml` VARCHAR(255) NOT NULL ,
`pct` VARCHAR(50) NOT NULL ,
`dtl` TEXT NOT NULL ,
`awc` VARCHAR(50) NOT NULL ,
`pd` INT(25) NOT NULL ,
`ppc` FLOAT(8,2) NOT NULL ,
PRIMARY KEY (`id`)) ENGINE = InnoDB;